# @package _global_
model:
    predictor:
        name: "SiameseModelSmall"

        cls: face_expression.model.SiameseModelSmall
        args:
            n_keypoints: 468
            beta_size: 10

            emb_size: 32
            hid_size: 32

            expression_size: 10
            jaw_pose_size: 3

    smplx_model:
        name: "SMPLXModel"
        
        cls: face_expression.smplx_model.ExpBodyModel
        args:
            bm_path: "${log.project_dir}/misc/body_models/smplx/SMPLX_NEUTRAL.npz"
            is_hand_pca: true
            num_pca_comps: 6